#!/bin/sh

echo "`date` - Starting Notify..."
export PORT=7867

if [ -x /apps2/notify_push/bin/x86_64/notify_push ] ; then
  /apps2/notify_push/bin/x86_64/notify_push /config/config.php &
  NOTIFY_PID=$!
  NOTIFY_LAST_MOD=$(date +%s -r /apps2/notify_push/bin/x86_64/notify_push )
fi

while true; do
  if [ -x /apps2/notify_push/bin/x86_64/notify_push ] ; then
    NOTIFY_LAST_MOD_NEW=$(date +%s -r /apps2/notify_push/bin/x86_64/notify_push )
    if  kill -0 $NOTIFY_PID 2> /dev/null ; then
      echo "`date` - Notify is still running..."
      if [ $NOTIFY_LAST_MOD -lt $NOTIFY_LAST_MOD_NEW ]; then
        echo "Notify binary was updated. Restarting..."
        kill $NOTIFY_PID
        /apps2/notify_push/bin/x86_64/notify_push /config/config.php &
        NOTIFY_PID=$!
        NOTIFY_LAST_MOD=$NOTIFY_LAST_MOD_NEW
      fi
    else
      echo "`date` - Notify died... restarting..."
      /apps2/notify_push/bin/x86_64/notify_push /config/config.php &
      NOTIFY_PID=$!
    fi
  fi

  CRON_PERIOD=<CRON_PERIOD>
  CRON_SECONDS=$((${CRON_PERIOD/m/}*60))
  sleep $CRON_SECONDS
done
